module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  plugins: ["jest"],
  extends: [
    "eslint:recommended",
    "plugin:jest/recommended",
    "plugin:jest/style",
  ],
  rules: {
    // ESLint (https://eslint.org/docs/rules/)
    curly: "error",
    "default-case": "error",
    "default-case-last": "error",
    eqeqeq: ["error", "always"],
    "id-blacklist": [
      "error",
      "any",
      "Number",
      "number",
      "String",
      "string",
      "Boolean",
      "boolean",
      "Undefined",
      "undefined",
    ],

    "new-parens": "error",
    "no-bitwise": "error",
    "no-caller": "error",
    "no-console": "error",
    "no-duplicate-imports": "error",
    "no-eval": "error",
    "no-extra-bind": "error",
    "no-invalid-this": "error",
    "no-magic-numbers": ["error", { ignore: [0, -1, 1, 2, 10] }],
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-octal-escape": "error",
    "no-return-await": "error",
    "no-sequences": "error",
    "no-shadow": ["error", { hoist: "all" }],
    "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-undef-init": "error",
    "no-underscore-dangle": "error",
    "no-var": "error",
    "no-void": "error",
    "object-shorthand": "error",
    "one-var": ["error", "never"],
    "padding-line-between-statements": [
      "error",
      { blankLine: "always", prev: "*", next: "return" },
    ],
    "prefer-const": "error",
    "prefer-object-spread": "error",
    "prefer-template": "error",
    radix: "error",
    "spaced-comment": ["error", "always", { markers: ["/"] }],
    yoda: "error",
  },
};
